# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 53b2455d055c95dc71a55cb9cd9406424542dac3f67de2a941e2d9289fd30085571aab935271b3b118ce53cf34893579a21a19e0cb7523fb5c17e202559a306d

test:
  secret_key_base: a83bee05190b364e38cda9c23b2a5b1cdffd0e08b62548bb18eb0de64b5d4a01c5f3cdf0269076c066e3c1645cba04c5af289b262b38f4da65ee56aa44506a66

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
